import pathlib,json,subprocess,uuid
root=pathlib.Path('/Users/mahdi/Documents/work/ioiv');e=root/'docs/security-remediation-2026-09-18/phase-8';old=json.loads((e/'environment.json').read_text());(e/'environment-pre-final-fix.json').write_text(json.dumps(old,indent=2));envpath=pathlib.Path(old['run'])/'env.json';env=json.loads(envpath.read_text());name='sana-phase8-final-'+uuid.uuid4().hex[:10];label='sana.task='+name
cid=subprocess.check_output(['docker','run','-d','--name',name,'--label',label,'-e','POSTGRES_PASSWORD=phase8_fixture','-e','POSTGRES_DB=phase1','-p','127.0.0.1::5432','postgres:16'],text=True).strip();port=subprocess.check_output(['docker','port',cid,'5432/tcp'],text=True).strip().split(':')[-1]
info={**old,'container':name,'containerId':cid,'label':label,'port':port};(e/'environment.json').write_text(json.dumps(info,indent=2));env.update(DATABASE_URL=f'postgresql://phase1_runtime:phase8_runtime@127.0.0.1:{port}/phase1',PHASE1_OWNER_URL=f'postgresql://postgres:phase8_fixture@127.0.0.1:{port}/phase1');envpath.write_text(json.dumps(env));subprocess.run(['docker','exec',cid,'sh','-c','until pg_isready -U postgres; do sleep 1; done'],check=True,stdout=subprocess.DEVNULL)
with (e/'fresh-final-db.log').open('w') as log:
 subprocess.run([str(pathlib.Path(old['source'])/'node_modules/.bin/prisma'),'migrate','deploy'],cwd=old['source'],env={**env,'DATABASE_URL':env['PHASE1_OWNER_URL']},stdout=log,stderr=subprocess.STDOUT,check=True)
 subprocess.run(['docker','exec',cid,'psql','-U','postgres','-d','phase1','-c',"CREATE ROLE phase1_runtime LOGIN PASSWORD 'phase8_runtime' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT"],stdout=log,stderr=subprocess.STDOUT,check=True)
 subprocess.run(['docker','exec','-i',cid,'psql','-v','ON_ERROR_STOP=1','-U','postgres','-d','phase1','-v','runtime_role=phase1_runtime'],input=(root/'prisma/facilities-runtime-role-grants.sql').read_bytes(),stdout=log,stderr=subprocess.STDOUT,check=True)
print('Fresh final30-migration database and canonical restricted role ready')
