import assert from "node:assert/strict";
import {randomInt} from "node:crypto";
import {createServer} from "node:http";
import {spawn,type ChildProcess} from "node:child_process";
import {mkdir} from "node:fs/promises";
import {resolve} from "node:path";
import {PrismaClient} from "@prisma/client";
const owner=new PrismaClient({datasources:{db:{url:process.env.PHASE1_OWNER_URL}}});
const servers:ChildProcess[]=[],logs:string[]=[],codes=new Set<string>();
let sends=0,lastCode="",outcome="ok";
const provider=createServer((req,res)=>{let body="";req.on("data",c=>body+=c);req.on("end",()=>{sends++;lastCode=new URLSearchParams(body).get("param1")!;codes.add(lastCode);if(outcome==="timeout")return;const reply=()=>{if(res.destroyed)return;res.writeHead(outcome==="failure"?500:200,{"content-type":"application/json"});res.end(outcome==="malformed"?'{}':'{"IsSuccess":true}');};if(outcome==="slow")setTimeout(reply,600);else reply();});});
async function listen(s:ReturnType<typeof createServer>){await new Promise<void>(r=>s.listen(0,"127.0.0.1",r));return (s.address() as {port:number}).port;}
async function start(timeout="1000"){const probe=createServer(),port=await listen(probe);await new Promise<void>(r=>probe.close(()=>r()));const base=`http://127.0.0.1:${port}`;
 const p=spawn(process.execPath,["node_modules/next/dist/bin/next","start","-H","127.0.0.1","-p",String(port)],{env:{...process.env,APP_URL:base,OTP_VERIFY_TRUST_PROXY:"false",OTP_MAX_REQUESTS_PER_IP_PER_WINDOW:"4",GHASEDAK_API_KEY:"synthetic-local-only",GHASEDAK_BASE_URL:`http://127.0.0.1:${(provider.address() as {port:number}).port}`,GHASEDAK_ALLOW_INSECURE_HTTP:"true",SMS_REQUEST_TIMEOUT_MS:timeout,NODE_OPTIONS:`--require=${resolve("prisma/tests/otp-verification/no-external-fetch.cjs")}`},stdio:["ignore","pipe","pipe"]});servers.push(p);let out="";for(const stream of [p.stdout,p.stderr])stream!.on("data",c=>{out+=c;logs.push(String(c));});const end=Date.now()+30000;while(!out.includes("Ready in")){assert.ok(Date.now()<end&&p.exitCode===null);await new Promise(r=>setTimeout(r,50));}console.log(JSON.stringify({pid:p.pid,port}));return base;}
function mobile(){return `095${randomInt(10000000,99999999)}`;}
async function reset(){await owner.$executeRaw`TRUNCATE "AuthVerifyBucket", "AuthRequestIntent"`;outcome="ok";sends=0;}
async function fixture(kind:string){const n=mobile();if(kind!=="unknown")await owner.admin.create({data:{mobile:n,name:"Synthetic R6 browser",role:"ADMIN",active:kind!=="inactive"}});return n;}
async function post(base:string,n:string,index=0){const at=performance.now();const r=await fetch(`${base}/api/auth/request-otp`,{method:"POST",headers:{origin:base,"content-type":"application/json","x-real-ip":`203.0.113.${index+1}`,"x-forwarded-for":`198.51.100.${index+1}`},body:JSON.stringify({mobile:n,mode:"admin"})});return {status:r.status,body:await r.json(),ms:performance.now()-at,cookie:r.headers.get("set-cookie")};}
async function main(){assert.equal(process.env.PHASE1_ISOLATED_DB,"true");const url=new URL(process.env.DATABASE_URL!);assert.equal(url.hostname,"127.0.0.1");assert.equal(url.username,"phase1_runtime");let closeBrowser:(()=>Promise<void>)|undefined;
try{console.log(JSON.stringify({providerPort:await listen(provider)}));const bases=[await start(),await start()];let expected:unknown;
 for(const mode of ["ok","slow","failure","malformed","timeout"]){await reset();outcome=mode;const ns=await Promise.all(["unknown","inactive","active"].map(fixture));const before={users:await owner.user.count(),admins:await owner.admin.count()};const rs=await Promise.all(ns.map((n,i)=>post(bases[i%2],n,i)));
  for(const r of rs){assert.equal(r.status,200);assert.equal(r.cookie,null);expected??=r.body;assert.deepEqual(r.body,expected);assert.ok(r.ms>=12900&&r.ms<18000,"response floor/healthy upper bound");}
  assert.ok(Math.max(...rs.map(r=>r.ms))-Math.min(...rs.map(r=>r.ms))<1500,"healthy timing spread");assert.equal(sends,1);assert.equal(await owner.otpCode.count({where:{mobile:{in:ns.slice(0,2)}}}),0);assert.equal(await owner.user.count(),before.users);assert.equal(await owner.admin.count(),before.admins);
  console.log(JSON.stringify({pass:"uniform status/body/no cookie and measured timing",provider:mode,durationsMs:rs.map(r=>Math.round(r.ms)),unknownInactiveOtp:0,sends}));
 }
 await reset();const ns=Array.from({length:12},mobile);const rs=await Promise.all(ns.map((n,i)=>post(bases[i%2],n,i)));assert.equal(rs.filter(r=>r.status===200).length,4);assert.equal(rs.filter(r=>r.status===429).length,8);assert.equal(sends,0);assert.equal(await owner.authRequestIntent.count(),4);assert.equal(await owner.otpCode.count({where:{mobile:{in:ns}}}),0);assert.equal(await owner.user.count({where:{mobile:{in:ns}}}),0);console.log("PASS12 distinct unknown probes/two processes/spoofed headers:4 admitted8 denied, no SMS/OTP/account");
 await reset();outcome="timeout";const maximum=await start("30000");const maximumNumbers=await Promise.all(["unknown","inactive","active"].map(fixture));const maximumResults=await Promise.all(maximumNumbers.map(n=>post(maximum,n)));for(const r of maximumResults){assert.equal(r.status,200);assert.deepEqual(r.body,expected);assert.ok(r.ms>=41900&&r.ms<48000);}assert.equal(sends,1);console.log(JSON.stringify({pass:"maximum30s provider timeout uniform42s floor",durationsMs:maximumResults.map(r=>Math.round(r.ms))}));
 const {chromium}=await import(process.env.PHASE1_PLAYWRIGHT!);const browser=await chromium.launch({headless:true,channel:"chrome"});closeBrowser=()=>browser.close();await mkdir(process.env.PHASE1_SCREENSHOTS!,{recursive:true});
 for(const width of [390,1440])for(const kind of ["unknown","inactive","active"]){await reset();outcome="timeout";const n=await fixture(kind),base=bases[0];const context=await browser.newContext({viewport:{width,height:900}});await context.route("**/*",(r:{request:()=>{url:()=>string};continue:()=>Promise<void>;abort:()=>Promise<void>})=>new URL(r.request().url()).origin===base?r.continue():r.abort());const page=await context.newPage();await page.goto(base+"/admin/login");await page.locator("#admin-mobile").fill(n);const response=page.waitForResponse((r:{url:()=>string})=>r.url().endsWith("/api/auth/request-otp"));await page.getByRole("button",{name:"دریافت کد تایید",exact:true}).click();assert.equal(await page.getByRole("button",{name:"در حال بررسی...",exact:true}).isDisabled(),true);assert.equal(await page.locator("#admin-mobile").isDisabled(),true);assert.equal((await response).status(),200);await page.getByRole("status").filter({hasText:"اگر این شماره مجاز باشد"}).waitFor();assert.equal(await page.locator("#admin-otp").getAttribute("aria-invalid"),null);assert.equal(await page.locator("#admin-otp").getAttribute("aria-describedby"),"admin-request-info");assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:`${process.env.PHASE1_SCREENSHOTS}/${kind}-${width}.png`});
  const verify=page.waitForResponse((r:{url:()=>string})=>r.url().endsWith("/api/auth/verify-otp"));await page.locator("#admin-otp").fill(kind==="active"?lastCode:"123456");await page.getByRole("button",{name:"ورود به پنل مدیریت",exact:true}).click();assert.equal((await verify).status(),kind==="active"?200:400);
  if(kind==="active"){await page.waitForURL((u:URL)=>u.pathname==="/admin");assert.ok((await context.cookies()).some((c:{name:string})=>c.name==="sana_session"));await page.reload();assert.equal(new URL(page.url()).pathname,"/admin");}else{await page.locator("#admin-otp-error").waitFor();assert.equal(await page.locator("#admin-otp").inputValue(),"");assert.equal((await context.cookies()).length,0);}
  await context.clearCookies();await page.goto(base+"/admin/login");await page.locator("#admin-mobile").fill(n);const denied=page.waitForResponse((r:{url:()=>string})=>r.url().endsWith("/api/auth/request-otp"));await page.getByRole("button",{name:"دریافت کد تایید",exact:true}).click();assert.equal((await denied).status(),429);await page.locator("#admin-mobile-error").waitFor();await page.reload();assert.equal(sends,kind==="active"?1:0);await context.close();console.log(`PASS ${width}px ${kind} accessible conditional code entry, verification, cooldown,refresh`);
 }
 for(const code of codes)assert.ok(!logs.join("").includes(code),"fixture OTP leaked");console.log("PASS fixture OTPs absent from logs");
}finally{try{await closeBrowser?.();}finally{for(const p of servers)if(p.exitCode===null&&p.signalCode===null){const done=new Promise<void>(r=>p.once("exit",()=>r()));const timer=setTimeout(()=>p.kill("SIGKILL"),5000);p.kill("SIGTERM");await done;clearTimeout(timer);}provider.closeAllConnections();await new Promise<void>(r=>provider.close(()=>r()));await owner.$disconnect();console.log("Owned browser/Next/provider stopped");}}}
main().catch(e=>{console.error(e);process.exitCode=1;});
