import assert from "node:assert/strict";
import {randomInt,randomUUID} from "node:crypto";
import {createServer as httpServer} from "node:http";
import {createServer} from "node:net";
import {spawn,type ChildProcess} from "node:child_process";
import {mkdir,readFile} from "node:fs/promises";
import {readFileSync} from "node:fs";
import {resolve} from "node:path";
import {SignJWT} from "jose";
import {PrismaClient} from "@prisma/client";
const owner=new PrismaClient({datasources:{db:{url:process.env.PHASE1_OWNER_URL}}});
const bytes=Buffer.from("%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\ntrailer\n<< /Root 1 0 R >>\nstartxref\n0\n%%EOF\n");
let scans=0,server:ChildProcess|undefined;
const sockets=new Set<import("node:net").Socket>();
const scanner=createServer(socket=>{sockets.add(socket);socket.on("close",()=>sockets.delete(socket));let data=Buffer.alloc(0),done=false;socket.on("data",chunk=>{data=Buffer.concat([data,chunk]);if(done||data.length<10)return;let at=10;while(data.length>=at+4){const n=data.readUInt32BE(at);at+=4;if(n===0){done=true;scans++;socket.end("stream: OK\0");return;}if(data.length<at+n)return;at+=n;}});});
async function listen(s:ReturnType<typeof httpServer>|ReturnType<typeof createServer>){await new Promise<void>(r=>s.listen(0,"127.0.0.1",r));return(s.address() as {port:number}).port;}
async function token(id:string){return new SignJWT({subjectId:id,kind:"admin"}).setProtectedHeader({alg:"HS256"}).setIssuedAt().setExpirationTime("30m").sign(new TextEncoder().encode(process.env.SESSION_SECRET!));}
async function main(){assert.equal(process.env.PHASE1_ISOLATED_DB,"true");assert.equal(new URL(process.env.DATABASE_URL!).hostname,"127.0.0.1");let closeBrowser:(()=>Promise<void>)|undefined;
try{
 const scannerPort=await listen(scanner),probe=httpServer(),port=await listen(probe);await new Promise<void>(r=>probe.close(()=>r()));const base=`http://127.0.0.1:${port}`;
 server=spawn(process.execPath,["node_modules/next/dist/bin/next","start","-H","127.0.0.1","-p",String(port)],{env:{...process.env,APP_URL:base,FACILITIES_CLAMAV_HOST:"127.0.0.1",FACILITIES_CLAMAV_PORT:String(scannerPort),FACILITIES_CLAMAV_TIMEOUT_MS:"1000",NODE_OPTIONS:`--require=${resolve("prisma/tests/otp-verification/no-external-fetch.cjs")}`},stdio:["ignore","pipe","pipe"]});let output="";server.stdout!.on("data",x=>output+=x);server.stderr!.on("data",x=>output+=x);const deadline=Date.now()+30000;while(!output.includes("Ready in")){assert.ok(Date.now()<deadline&&server.exitCode===null);await new Promise(r=>setTimeout(r,50));}console.log(JSON.stringify({pid:server.pid,port,scannerPort}));
 const {chromium}=await import(process.env.PHASE1_PLAYWRIGHT!);const browser=await chromium.launch({headless:true,channel:"chrome"});closeBrowser=()=>browser.close();await mkdir(process.env.PHASE1_SCREENSHOTS!,{recursive:true});

 async function facilitiesFixture() {
  const prefix=`r11browser${randomUUID().replaceAll("-","")}`;
  const sql=readFileSync("prisma/tests/facilities-m6-payment.integration.sql","utf8").split('INSERT INTO "FacilitiesPaymentAttempt"')[0].replace(/\\set[^\n]*\n/,"").replace("BEGIN;","").replace(/m6-payment/g,prefix).replace("M6 payment test supplier","تأمین‌کننده آزمایشی "+prefix.slice(-6)).replace("M6 payment test intake","فراخوان آزمایشی "+prefix.slice(-6));
  await owner.$transaction(async tx=>{for(const st of sql.split(";").map(s=>s.trim()).filter(Boolean)){if(st.includes('INSERT INTO "FacilitiesProgramConfiguration"'))continue;const q=st.replace("09900000061",`096${randomInt(10000000,99999999)}`).replace("09900000062",`096${randomInt(10000000,99999999)}`);if(st.includes('INSERT INTO "FacilitiesApplication"')){await tx.$executeRawUnsafe("SET LOCAL session_replication_role=replica");await tx.$executeRawUnsafe(q);await tx.facilitiesApplication.update({where:{id:`${prefix}-application`},data:{status:"UNDER_REVIEW"}});await tx.$executeRawUnsafe("SET LOCAL session_replication_role=origin");}else await tx.$executeRawUnsafe(q);}});
  return `${prefix}-application`;
 }
 for(const width of [390,1440]){
  const admin=await owner.admin.create({data:{mobile:`096${randomInt(10000000,99999999)}`,name:"کارشناس آزمایشی",role:"SUPER_ADMIN"}});
  const user=await owner.user.create({data:{mobile:`096${randomInt(10000000,99999999)}`}});
  const app=await owner.application.create({data:{userId:user.id,mobile:user.mobile,companyNationalId:randomUUID(),companyName:"شرکت آزمایشی",status:"SUBMITTED"}});
  const context=await browser.newContext({viewport:{width,height:900}});const cookie={name:"sana_session",value:await token(admin.id),url:base,httpOnly:true,sameSite:"Lax" as const};await context.addCookies([cookie]);
  await context.route("**/*",(route:{request:()=>{url:()=>string};continue:()=>Promise<void>;abort:()=>Promise<void>})=>new URL(route.request().url()).origin===base?route.continue():route.abort());
  const page=await context.newPage();await page.goto(base+`/admin/submissions/${app.id}`);await page.getByRole("button",{name:"تغییر وضعیت",exact:true}).waitFor();await page.locator(".toast").first().waitFor({state:"hidden"});await page.screenshot({path:`${process.env.PHASE1_SCREENSHOTS}/legacy-initial-${width}.png`});
  await page.getByRole("button",{name:"تغییر وضعیت",exact:true}).click();await page.getByRole("button",{name:"انصراف",exact:true}).click();await page.getByRole("button",{name:"تغییر وضعیت",exact:true}).click();await page.locator('select[name="status"]').selectOption("NEEDS_EDIT");await page.locator('textarea[name="note"]').fill("یادداشت صفحه قدیمی");
  const competing=await context.request.post(base+"/api/admin/submissions/status",{multipart:{applicationId:app.id,expectedStatus:"SUBMITTED",expectedVersion:"0",status:"UNDER_REVIEW",note:"یادداشت مدیر دیگر"}});assert.equal(competing.status(),200);
  await page.getByRole("button",{name:"تغییر وضعیت",exact:true}).click();await page.getByRole("button",{name:"تایید و ذخیره",exact:true}).click();await page.getByText(/اطلاعات یا فایل پرونده تغییر کرده است/).first().waitFor();assert.equal((await owner.application.findUniqueOrThrow({where:{id:app.id}})).adminNote,"یادداشت مدیر دیگر");await page.locator('input[name="expectedVersion"][value="1"]').waitFor({state:"attached"});await page.locator(".toast").first().waitFor({state:"hidden"});await page.screenshot({path:`${process.env.PHASE1_SCREENSHOTS}/legacy-conflict-${width}.png`});
  await page.locator('select[name="status"]').selectOption("VALIDATION_COMPLETED");await page.locator('input[name="certificate"]').setInputFiles({name:"certificate.pdf",mimeType:"application/pdf",buffer:bytes});await page.getByRole("button",{name:"تغییر وضعیت",exact:true}).click();await page.getByRole("button",{name:"تایید و ذخیره",exact:true}).click();await page.waitForURL(base+"/admin/submissions");
  await page.goto(base+`/admin/submissions/${app.id}`);const first=await owner.legacyFileBinding.findUniqueOrThrow({where:{applicationId_slotKey:{applicationId:app.id,slotKey:"validationCertificate"}},include:{currentFile:true}});assert.deepEqual(await readFile(first.currentFile.storagePath),bytes);
  await page.locator('#replacement-validation-certificate').setInputFiles({name:"replacement.pdf",mimeType:"application/pdf",buffer:bytes});await page.getByRole("button",{name:"بارگذاری گواهی",exact:true}).click();await page.getByText("گواهی با موفقیت ذخیره شد").first().waitFor();const current=await owner.legacyFileBinding.findUniqueOrThrow({where:{id:first.id},include:{currentFile:true}});assert.notEqual(current.currentFileId,first.currentFileId);await page.locator(`a[href="/api/files/${current.currentFileId}"]`).waitFor();await page.locator(".toast").first().waitFor({state:"hidden"});await page.screenshot({path:`${process.env.PHASE1_SCREENSHOTS}/certificate-refreshed-${width}.png`});
  await context.clearCookies();await page.locator('#replacement-validation-certificate').setInputFiles({name:"expired.pdf",mimeType:"application/pdf",buffer:bytes});await page.getByRole("button",{name:"بارگذاری گواهی",exact:true}).click();await page.getByText(/نشست شما پایان یافته است/).first().waitFor();await page.locator(".toast").first().waitFor({state:"hidden"});await page.screenshot({path:`${process.env.PHASE1_SCREENSHOTS}/legacy-expired-${width}.png`});await context.addCookies([cookie]);
  const facilityId=await facilitiesFixture();await page.goto(base+`/admin/facilities/applications/${facilityId}`);await page.getByRole("button",{name:"درخواست اصلاح",exact:true}).waitFor();await page.locator('textarea').fill("یادداشت قدیمی برای اصلاح");const other=await context.newPage();await other.goto(base+`/admin/facilities/applications/${facilityId}`);await other.locator('textarea').fill("تایید مدیر دیگر");await other.getByRole("button",{name:"پایان فرآیند اعتبارسنجی",exact:true}).click();await other.getByText("در وضعیت فعلی اقدام جدیدی برای این پرونده وجود ندارد.").waitFor();await page.getByRole("button",{name:"درخواست اصلاح",exact:true}).click();await page.getByText(/اطلاعات یا فایل پرونده تغییر کرده است/).first().waitFor();await page.getByText("در وضعیت فعلی اقدام جدیدی برای این پرونده وجود ندارد.").waitFor();await page.locator(".toast").first().waitFor({state:"hidden"});await page.screenshot({path:`${process.env.PHASE1_SCREENSHOTS}/facilities-conflict-${width}.png`});assert.equal(await owner.facilitiesCorrectionRequest.count({where:{applicationId:facilityId}}),0);assert.equal(await owner.facilitiesStatusHistory.count({where:{applicationId:facilityId}}),1);await other.close();
  const expiredFacility=await facilitiesFixture();await page.goto(base+`/admin/facilities/applications/${expiredFacility}`);await page.getByRole("button",{name:"پایان فرآیند اعتبارسنجی",exact:true}).waitFor();await context.clearCookies();await page.getByRole("button",{name:"پایان فرآیند اعتبارسنجی",exact:true}).click();await page.getByText(/نشست شما پایان یافته است/).first().waitFor();assert.equal(await owner.facilitiesStatusHistory.count({where:{applicationId:expiredFacility}}),0);await page.locator(".toast").first().waitFor({state:"hidden"});await page.screenshot({path:`${process.env.PHASE1_SCREENSHOTS}/facilities-expired-${width}.png`});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await context.close();console.log(`PASS ${width}px legacy stale conflict, certificate commit/refresh, expired401; facilities production serialized409/401 and one preserved decision`);
 }
 console.log(`PASS controlled INSTREAM scans ${scans}; external fetch blocked`);
}finally{await closeBrowser?.();if(server&&server.exitCode===null){const stopped=new Promise<void>(r=>server!.once("exit",()=>r()));const kill=setTimeout(()=>server!.kill("SIGKILL"),5000);server.kill("SIGTERM");await stopped;clearTimeout(kill);}for(const socket of sockets)socket.destroy();await new Promise<void>(r=>scanner.close(()=>r()));await owner.$disconnect();console.log("Owned Next/browser/scanner stopped");}}
main().catch(error=>{console.error(error);process.exitCode=1;});
