"use server";

import { Prisma } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { db } from "@/lib/db";
import { requireSession } from "@/lib/auth/session";
import { ActionError } from "@/lib/actions/auth";
import { createOwnedFacilitiesFileBinding } from "@/lib/facilities-files/service";

const requiredSlots = ["questionnaire", "licences", "active-contracts", "insurance", "trial-general", "trial-subsidiary", "credit-company", "credit-ceo", "credit-board", "vat-1404"];
function slotFor(kind: string, year?: number) { return year ? `${kind}-${year}` : kind; }

async function eligible(userId: string) {
  const [programme, company] = await Promise.all([db.facilitiesProgramConfiguration.findUnique({ where: { program: "FACILITIES" } }), db.company.findUnique({ where: { userId } })]);
  if (!programme?.isEnabled) throw new ActionError("ثبت درخواست تسهیلات در حال حاضر فعال نیست", 403);
  if (!company?.profileCompletedAt) throw new ActionError("ابتدا پروفایل شرکت و مدارک آن را تکمیل کنید", 403);
  return company;
}
export async function getFacilitiesWizard() {
  const session = await requireSession("user"); const company = await eligible(session.subjectId);
  const intakes = await db.facilityIntake.findMany({ where: { isEnabled: true, supplierConfigurations: { some: { isEnabled: true, questionnaireTemplateVersion: { is: { publishedAt: { not: null }, retiredAt: null, storedFile: { is: { scanStatus: "PASSED", fileType: { in: ["DOC", "DOCX"] } } } } } } } }, include: { supplierConfigurations: { where: { isEnabled: true, questionnaireTemplateVersion: { is: { publishedAt: { not: null }, retiredAt: null, storedFile: { is: { scanStatus: "PASSED", fileType: { in: ["DOC", "DOCX"] } } } } } }, include: { supplier: true, questionnaireTemplateVersion: true } } } });
  const applications = await db.facilitiesApplication.findMany({ where: { userId: session.subjectId, companyId: company.id }, include: { intake: true, officers: true, intakeSupplier: { include: { supplier: true } }, questionnaireTemplateVersion: true, fileBindings: { include: { currentUpload: { include: { storedFile: true } } } } } }); return { company, intakes, applications };
}
export async function createFacilitiesDraft(input: { intakeId: string; intakeSupplierId: string; facilityType: "FIXED_CAPITAL" | "WORKING_CAPITAL"; requestedAmountRial: string }) {
  const session = await requireSession("user"); const company = await eligible(session.subjectId); const amount = new Prisma.Decimal(input.requestedAmountRial);
  if (amount.isNegative()) throw new ActionError("مبلغ درخواستی معتبر نیست");
  try { const application = await db.$transaction(async (tx) => { const config = await tx.facilityIntakeSupplier.findFirst({ where: { id: input.intakeSupplierId, intakeId: input.intakeId, isEnabled: true }, include: { intake: true, questionnaireTemplateVersion: { include: { storedFile: true } } } }); if (!config?.intake.isEnabled || !config.questionnaireTemplateVersion || config.questionnaireTemplateVersion.retiredAt || !config.questionnaireTemplateVersion.publishedAt || config.questionnaireTemplateVersion.storedFile.scanStatus !== "PASSED" || !["DOC", "DOCX"].includes(config.questionnaireTemplateVersion.storedFile.fileType)) throw new ActionError("تنظیمات انتخاب‌شده دیگر معتبر نیست؛ صفحه را تازه‌سازی کنید", 409); if (amount.gt(config.intake.maximumAmountRial)) throw new ActionError("مبلغ درخواستی از سقف دوره بیشتر است"); const app = await tx.facilitiesApplication.create({ data: { userId: session.subjectId, companyId: company.id, intakeId: config.intakeId, intakeSupplierId: config.id, questionnaireTemplateVersionId: config.questionnaireTemplateVersion.id, facilityType: input.facilityType, requestedAmountRial: amount, maximumAmountRialSnapshot: config.intake.maximumAmountRial, paymentEnabledSnapshot: config.intake.paymentEnabled, paymentAmountTomanSnapshot: config.intake.paymentEnabled ? config.intake.paymentAmountToman : null, paymentTermsVersionSnapshot: config.intake.paymentTermsVersion, companySnapshot: { create: { name: company.name, nationalId: company.nationalId, registrationNumber: company.registrationNumber, registrationPlace: company.registrationPlace, registrationDate: company.registrationDate, registeredCapitalRial: company.registeredCapitalRial, contactFullName: company.contactFullName, contactNationalCode: company.contactNationalCode } }, shareholders: { create: (await tx.companyShareholder.findMany({ where: { companyId: company.id } })).map((x) => ({ fullName: x.fullName, ownershipPercentage: x.ownershipPercentage })) }, officers: { create: (await tx.companyOfficer.findMany({ where: { companyId: company.id } })).map((x) => ({ fullName: x.fullName, position: x.position, isChiefExecutive: x.isChiefExecutive })) } } }); await tx.facilitiesAuditLog.create({ data: { applicationId: app.id, actorType: "USER", actorId: session.subjectId, action: "APPLICATION_CREATED", entityType: "FacilitiesApplication", entityId: app.id, metadata: {} } }); return app; }); revalidatePath("/dashboard/facilities-application"); return application; } catch (error) { if ((error as { code?: string }).code === "P2002") throw new ActionError("برای این دوره قبلاً یک درخواست ایجاد شده است", 409); throw error; }
}
export async function ensureFacilitiesApplicationSlot(input: { applicationId: string; kind: string; year?: number }) { const session = await requireSession("user"); const application = await db.facilitiesApplication.findFirst({ where: { id: input.applicationId, userId: session.subjectId, status: "DRAFT" } }); if (!application) throw new ActionError("دسترسی به پیش‌نویس امکان‌پذیر نیست", 403); const key = slotFor(input.kind, input.year); if (!/^(questionnaire|licences|active-contracts|insurance|trial-general|trial-subsidiary|credit-company|credit-ceo|credit-board|vat|tax|financial|questionnaire-attachment)(-14(0[2-5]))?$/.test(key) && !key.startsWith("questionnaire-attachment-")) throw new ActionError("نوع مدرک معتبر نیست"); const existing = await db.facilitiesFileBinding.findFirst({ where: { applicationId: application.id, slotKey: key } }); return existing ?? createOwnedFacilitiesFileBinding({ userId: session.subjectId, companyId: application.companyId, applicationId: application.id, slotKey: key }); }
export async function saveFacilitiesDraftDetails(input: { applicationId: string; employeeCount: number; boardOfficerId: string }) { const session = await requireSession("user"); const app = await db.facilitiesApplication.findFirst({ where: { id: input.applicationId, userId: session.subjectId, status: "DRAFT" }, include: { fileBindings: { include: { currentUpload: true } }, officers: true } }); if (!app) throw new ActionError("دسترسی به پیش‌نویس امکان‌پذیر نیست", 403); if (!Number.isInteger(input.employeeCount) || input.employeeCount < 0 || !app.officers.some((x) => x.id === input.boardOfficerId && !x.isChiefExecutive)) throw new ActionError("اطلاعات منابع انسانی یا عضو هیئت‌مدیره معتبر نیست"); const ready = app.fileBindings.filter((x) => x.currentUpload?.lifecycleStatus === "PASSED"); if (requiredSlots.some((key) => !ready.some((x) => x.slotKey === key)) || !ready.some((x) => x.slotKey.startsWith("tax-")) || !ready.some((x) => x.slotKey.startsWith("financial-"))) throw new ActionError("همه مدارک الزامی باید با موفقیت بررسی شده باشند"); await db.$transaction(async (tx) => { for (const binding of ready) { const [kind, yearText] = binding.slotKey.split("-"); await tx.facilitiesApplicationEvidence.upsert({ where: { bindingId: binding.id }, create: { applicationId: app.id, bindingId: binding.id, kind: binding.slotKey.startsWith("tax-") ? "tax" : binding.slotKey.startsWith("financial-") ? "financial" : binding.slotKey.startsWith("vat-") ? "vat" : binding.slotKey, year: ["tax", "financial", "vat"].includes(kind) ? Number(yearText) : undefined, officerId: binding.slotKey === "credit-board" ? input.boardOfficerId : undefined, employeeCount: binding.slotKey === "insurance" ? input.employeeCount : undefined }, update: { officerId: binding.slotKey === "credit-board" ? input.boardOfficerId : undefined, employeeCount: binding.slotKey === "insurance" ? input.employeeCount : undefined } }); } await tx.facilitiesAuditLog.create({ data: { applicationId: app.id, actorType: "USER", actorId: session.subjectId, action: "APPLICATION_UPDATED", entityType: "FacilitiesApplication", entityId: app.id, metadata: {} } }); }); revalidatePath("/dashboard/facilities-application"); }
