import assert from "node:assert/strict";
import { randomInt } from "node:crypto";
import { createServer, type ServerResponse } from "node:http";
import { spawn,type ChildProcess } from "node:child_process";
import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import { PrismaClient } from "@prisma/client";
const owner=new PrismaClient({datasources:{db:{url:process.env.PHASE1_OWNER_URL}}});const servers:ChildProcess[]=[];const logs:string[]=[];
const codes=new Set<string>();
let count=0,mode="ok",lastCode="";let held:ServerResponse|undefined;
const provider=createServer((req,res)=>{let body="";req.on("data",c=>body+=c);req.on("end",()=>{count++;lastCode=new URLSearchParams(body).get("param1")!;assert.match(lastCode,/^\d{6}$/);codes.add(lastCode);if(mode==="hold"||mode==="timeout"){held=res;return;}res.writeHead(mode==="failure"?500:200,{"content-type":"application/json"});res.end(mode==="malformed"?'{}':JSON.stringify({IsSuccess:true}));});});
async function start(proxy=false,databaseUrl=process.env.DATABASE_URL){const probe=createServer();await new Promise<void>(r=>probe.listen(0,"127.0.0.1",r));const port=(probe.address() as {port:number}).port;await new Promise<void>(r=>probe.close(()=>r()));const base=`http://127.0.0.1:${port}`;
 const p=spawn(process.execPath,["node_modules/next/dist/bin/next","start","-H","127.0.0.1","-p",String(port)],{env:{...process.env,DATABASE_URL:databaseUrl,APP_URL:base,OTP_VERIFY_TRUST_PROXY:String(proxy),OTP_MAX_REQUESTS_PER_IP_PER_WINDOW:"8",GHASEDAK_API_KEY:"synthetic-local-only",GHASEDAK_BASE_URL:`http://127.0.0.1:${(provider.address() as {port:number}).port}`,GHASEDAK_ALLOW_INSECURE_HTTP:"true",SMS_REQUEST_TIMEOUT_MS:"1000",NODE_OPTIONS:`--require=${resolve("prisma/tests/otp-verification/no-external-fetch.cjs")}`},stdio:["ignore","pipe","pipe"]});servers.push(p);let output="";const capture=(c:Buffer)=>{output+=c;logs.push(String(c));};p.stdout.on("data",capture);p.stderr.on("data",capture);const deadline=Date.now()+30000;while(!output.includes("Ready in")){assert.ok(Date.now()<deadline&&p.exitCode===null,"server startup failed");await new Promise(r=>setTimeout(r,50));}console.log(JSON.stringify({serverPid:p.pid,port,proxy}));return base;}
async function reset(){await owner.$executeRaw`TRUNCATE "AuthVerifyBucket", "AuthRequestIntent"`;count=0;held=undefined;mode="ok";}
function mobile(){return `093${randomInt(10000000,99999999)}`;}
function post(base:string,number:string,headers:Record<string,string>={}){return fetch(`${base}/api/auth/request-otp`,{method:"POST",headers:{origin:base,"content-type":"application/json",...headers},body:JSON.stringify({mobile:number,mode:"user"})});}
async function waitFor(check:()=>boolean){const end=Date.now()+10000;while(!check()){assert.ok(Date.now()<end,"fixture barrier timeout");await new Promise(r=>setTimeout(r,10));}}
async function main(){assert.equal(process.env.PHASE1_ISOLATED_DB,"true");assert.equal(new URL(process.env.DATABASE_URL!).hostname,"127.0.0.1");let closeBrowser:(()=>Promise<void>)|undefined;
 try{
  await new Promise<void>(r=>provider.listen(0,"127.0.0.1",r));console.log(JSON.stringify({providerPort:(provider.address() as {port:number}).port}));
  const bases=[await start(),await start()];const base=bases[0];
  await reset();const number=mobile();mode="hold";const pending=post(base,number);await waitFor(()=>!!held);const duplicates=await Promise.all(Array.from({length:7},(_,i)=>post(bases[i%2],number)));assert.ok(duplicates.every(r=>r.status===429));assert.equal(count,1);held!.end(JSON.stringify({IsSuccess:true}));assert.equal((await pending).status,200);assert.equal(await owner.otpCode.count({where:{mobile:number}}),1);console.log("PASS eight HTTP requests/two production Next processes: one dispatch during slow provider");
  for(const outcome of ["failure","malformed","timeout"]){await reset();mode=outcome;const n=mobile();const response=await post(base,n);assert.equal(response.status,200);assert.ok((await response.json()).warning);assert.equal((await post(bases[1],n)).status,429);assert.equal(count,1);held?.destroy();console.log(`PASS ${outcome}: uncertain warning, quota retained, no retry`);}
  await reset();for(let i=0;i<8;i++)assert.equal((await post(base,mobile(),{"x-real-ip":`203.0.113.${i+1}`,"x-forwarded-for":`198.51.100.${i+1}`})).status,200);assert.equal((await post(base,mobile(),{"x-real-ip":"203.0.113.99"})).status,429);assert.equal(count,8);console.log("PASS unqualified/spoofed headers share unknown quota");
  const trusted=await start(true);await reset();for(let i=0;i<8;i++)assert.equal((await post(trusted,mobile(),{"x-real-ip":"203.0.113.8"})).status,200);assert.equal((await post(trusted,mobile(),{"x-real-ip":"203.0.113.8","x-forwarded-for":"203.0.113.99"})).status,429);assert.equal((await post(trusted,mobile(),{"x-real-ip":"203.0.113.9"})).status,200);console.log("PASS explicitly qualified X-Real-IP quota; XFF ignored (fixture only)");
  const {chromium}=await import(process.env.PHASE1_PLAYWRIGHT!);const browser=await chromium.launch({headless:true,channel:"chrome"});closeBrowser=()=>browser.close();await mkdir(process.env.PHASE1_SCREENSHOTS!,{recursive:true});
  for(const width of [390,1440])for(const userMode of ["user","admin"]){
   await reset();mode="timeout";const n=mobile();if(userMode==="admin")await owner.admin.create({data:{mobile:n,name:"Synthetic phase5 admin",role:"ADMIN"}});
   const context=await browser.newContext({viewport:{width,height:900}});await context.route("**/*",(route:{request:()=>{url:()=>string};continue:()=>Promise<void>;abort:()=>Promise<void>})=>new URL(route.request().url()).origin===base?route.continue():route.abort());const page=await context.newPage();let requests=0;page.on("request",(r:{url:()=>string})=>{if(r.url().endsWith("/api/auth/request-otp"))requests++;});
   await page.goto(`${base}${userMode==="admin"?"/admin/login":"/"}`);await page.locator(userMode==="admin"?"#admin-mobile":"#mobile").fill(n);
   const response=page.waitForResponse((r:{url:()=>string})=>r.url().endsWith("/api/auth/request-otp"));await page.getByRole("button",{name:"دریافت کد تایید",exact:true}).click();await waitFor(()=>!!held);
   assert.equal(await page.getByRole("button",{name:userMode==="admin"?"در حال بررسی...":"در حال ارسال...",exact:true}).isDisabled(),true);
   assert.equal((await response).status(),200);held?.destroy();await page.getByRole(userMode==="admin"?"status":"alert").filter({hasText:userMode==="admin"?"اگر این شماره مجاز باشد":"ارسال کد تأیید نشد"}).first().waitFor();assert.equal(requests,1);assert.equal(count,1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
   // A may-have-arrived code remains usable even after timeout. Value stays in
   // fixture memory only; never logs/screenshots/evidence.
   const code=lastCode;const verify=page.waitForResponse((r:{url:()=>string})=>r.url().endsWith("/api/auth/verify-otp"));
   await page.screenshot({path:`${process.env.PHASE1_SCREENSHOTS}/${userMode}-uncertain-${width}.png`,fullPage:true});
   if(userMode==="admin"){await page.locator("#admin-otp").fill(code);await page.getByRole("button",{name:"ورود به پنل مدیریت",exact:true}).click();}else for(let i=0;i<6;i++)await page.getByRole("textbox",{name:`رقم ${i+1} کد تایید`,exact:true}).fill(code[i]);
   assert.equal((await verify).status(),200);await page.waitForURL((u:URL)=>userMode==="admin"?u.pathname==="/admin":u.pathname.startsWith("/dashboard"));assert.ok((await context.cookies()).some((c:{name:string})=>c.name==="sana_session"));await context.clearCookies();await page.goto(`${base}${userMode==="admin"?"/admin/login":"/"}`);await page.locator(userMode==="admin"?"#admin-mobile":"#mobile").fill(n);
   const denied=page.waitForResponse((r:{url:()=>string})=>r.url().endsWith("/api/auth/request-otp"));await page.getByRole("button",{name:"دریافت کد تایید",exact:true}).click();assert.equal((await denied).status(),429);await page.getByRole("alert").filter({hasText:"تعداد درخواست‌های کد"}).first().waitFor();assert.equal(count,1);await page.reload();assert.equal(count,1);await context.close();console.log(`PASS ${width}px ${userMode}: loading, uncertain OTP entry, actual cookie,429/refresh no redispatch, accessible RTL`);
  }
  const probe=createServer();await new Promise<void>(r=>probe.listen(0,"127.0.0.1",r));const port=(probe.address() as {port:number}).port;await new Promise<void>(r=>probe.close(()=>r()));const u=new URL(process.env.DATABASE_URL!);u.port=String(port);u.searchParams.set("connect_timeout","1");const down=await start(false,u.toString());const before=count;assert.equal((await post(down,mobile())).status,503);assert.equal(count,before);console.log("PASS actual unavailable DB503/no provider dispatch");
  for(const code of codes)assert.ok(!logs.join("").includes(code),"OTP leaked to server logs");console.log("PASS captured server logs exclude every fixture OTP");
 }finally{try{await closeBrowser?.();}finally{for(const p of servers)if(p.exitCode===null&&p.signalCode===null){const ended=new Promise<void>(r=>p.once("exit",()=>r()));const timer=setTimeout(()=>p.kill("SIGKILL"),5000);p.kill("SIGTERM");await ended;clearTimeout(timer);}provider.closeAllConnections();await new Promise<void>(r=>provider.close(()=>r()));await owner.$disconnect();console.log("Owned browser, Next servers and provider stopped");}}
}main().catch(e=>{console.error(e);process.exitCode=1;});
