"use client";
import { useState, useTransition } from "react";
import { showToast } from "@/components/ui/toast";
import { saveFacilitiesProgramme, saveFacilityIntake, saveFacilityIntakeSupplier } from "@/lib/actions/facilities-config";

type Supplier = { id: string; name: string; templates: { id: string; versionLabel: string; publishedAt: string | null; storedFile: { originalName: string } }[] };
type Intake = { id: string; name: string; isEnabled: boolean; maximumAmountRial: string; paymentEnabled: boolean; paymentAmountToman: number; supplierConfigurations: { supplierId: string; isEnabled: boolean; questionnaireTemplateVersionId: string | null }[] };
export function FacilitiesConfiguration({ initial }: { initial: { programmeEnabled: boolean; suppliers: Supplier[]; intakes: Intake[] } }) {
  const [programmeEnabled, setProgrammeEnabled] = useState(initial.programmeEnabled); const [pending, start] = useTransition();
  const report = (fn: () => Promise<unknown>, message: string) => start(async () => { try { await fn(); showToast({ type: "success", message }); } catch (error) { showToast({ type: "error", message: error instanceof Error ? error.message : "ذخیره ناموفق بود" }); } });
  async function uploadTemplate(form: HTMLFormElement) { const data = new FormData(form); data.set("idempotencyKey", crypto.randomUUID().replaceAll("-", "")); try { const response = await fetch("/api/admin/facilities/questionnaire-templates", { method: "POST", body: data }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "بارگذاری ناموفق بود"); form.reset(); showToast({ type: "success", message: "نسخه خصوصی پرسشنامه ثبت شد؛ صفحه را تازه‌سازی کنید" }); } catch (error) { showToast({ type: "error", message: error instanceof Error ? error.message : "بارگذاری ناموفق بود" }); } }
  return <div className="space-y-5">
    <section className="panel"><h2>دسترسی برنامه</h2><p>این تنظیم فقط در پیکربندی ثبت می‌شود؛ در M4 هیچ مسیر یا فرم متقاضی فعال نمی‌شود.</p><label className="checkbox-row"><input type="checkbox" checked={programmeEnabled} onChange={(e) => setProgrammeEnabled(e.target.checked)} /> فعال بودن برنامه تسهیلات</label><button className="button button--primary" disabled={pending} onClick={() => report(() => saveFacilitiesProgramme({ isEnabled: programmeEnabled }), "تنظیم برنامه ذخیره شد")}>ذخیره</button></section>
    <section className="panel"><h2>فراخوان جدید</h2><form className="profile-grid" onSubmit={(e) => { e.preventDefault(); const data = new FormData(e.currentTarget); report(() => saveFacilityIntake({ name: data.get("name"), maximumAmountRial: data.get("maximumAmountRial"), paymentAmountToman: data.get("paymentAmountToman"), isEnabled: data.get("isEnabled") === "on", paymentEnabled: data.get("paymentEnabled") === "on" }), "فراخوان ثبت شد"); }}><label>نام فراخوان<input name="name" required /></label><label>حداکثر مبلغ (ریال)<input name="maximumAmountRial" inputMode="numeric" defaultValue="500000000000" required /></label><label>مبلغ پرداخت (تومان)<input name="paymentAmountToman" inputMode="numeric" defaultValue="3000000" required /></label><label className="checkbox-row"><input name="isEnabled" type="checkbox" /> فعال</label><label className="checkbox-row"><input name="paymentEnabled" type="checkbox" defaultChecked /> پرداخت فعال</label><button className="button button--primary" disabled={pending}>ثبت فراخوان</button></form></section>
    <section className="panel"><h2>نسخه‌های پرسشنامه تأمین‌کنندگان</h2><p>هر بارگذاری یک نسخه جدید و تغییرناپذیر است. تنها فایل Word بررسی‌شده و اسکن‌شده پذیرفته می‌شود.</p>{initial.suppliers.map((supplier) => <article className="status-card" key={supplier.id}><h3>{supplier.name}</h3><ul>{supplier.templates.length ? supplier.templates.map((template) => <li key={template.id}>{template.versionLabel} — {template.storedFile.originalName}</li>) : <li>هنوز نسخه‌ای ثبت نشده است.</li>}</ul><form className="profile-row" onSubmit={(event) => { event.preventDefault(); uploadTemplate(event.currentTarget); }}><input type="hidden" name="supplierId" value={supplier.id} /><label>شماره نسخه<input name="versionLabel" required maxLength={80} placeholder="برای نمونه: ۱۴۰۵-۱" /></label><label>فایل Word<input name="file" type="file" accept=".doc,.docx" required /></label><button className="button button--ghost" disabled={pending}>بارگذاری نسخه Word</button></form></article>)}</section>
    <section className="panel"><h2>فراخوان‌ها و تأمین‌کنندگان</h2>{initial.intakes.length ? initial.intakes.map((intake) => <article className="status-card" key={intake.id}><h3>{intake.name}</h3><form className="profile-grid" onSubmit={(e) => { e.preventDefault(); const data = new FormData(e.currentTarget); report(() => saveFacilityIntake({ id: intake.id, name: data.get("name"), maximumAmountRial: data.get("maximumAmountRial"), paymentAmountToman: data.get("paymentAmountToman"), isEnabled: data.get("isEnabled") === "on", paymentEnabled: data.get("paymentEnabled") === "on" }), "تنظیمات فراخوان ذخیره شد"); }}><label>نام فراخوان<input name="name" defaultValue={intake.name} required /></label><label>حداکثر مبلغ (ریال)<input name="maximumAmountRial" defaultValue={intake.maximumAmountRial} inputMode="numeric" required /></label><label>مبلغ پرداخت (تومان)<input name="paymentAmountToman" defaultValue={intake.paymentAmountToman} inputMode="numeric" required /></label><label className="checkbox-row"><input type="checkbox" name="isEnabled" defaultChecked={intake.isEnabled} /> فعال</label><label className="checkbox-row"><input type="checkbox" name="paymentEnabled" defaultChecked={intake.paymentEnabled} /> پرداخت فعال</label><button className="button button--ghost" disabled={pending}>ذخیره فراخوان</button></form>{initial.suppliers.map((supplier) => { const current = intake.supplierConfigurations.find((item) => item.supplierId === supplier.id); return <form className="profile-row" key={supplier.id} onSubmit={(e) => { e.preventDefault(); const data = new FormData(e.currentTarget); report(() => saveFacilityIntakeSupplier({ intakeId: intake.id, supplierId: supplier.id, isEnabled: data.get("isEnabled") === "on", questionnaireTemplateVersionId: data.get("template") || null }), "تنظیم تأمین‌کننده ذخیره شد"); }}><span>{supplier.name}</span><select name="template" defaultValue={current?.questionnaireTemplateVersionId ?? ""} aria-label={`نسخه پرسشنامه ${supplier.name}`}><option value="">نسخه را انتخاب کنید</option>{supplier.templates.map((template) => <option key={template.id} value={template.id}>{template.versionLabel}</option>)}</select><label className="checkbox-row"><input type="checkbox" name="isEnabled" defaultChecked={current?.isEnabled} /> فعال</label><button className="button button--ghost" disabled={pending}>ذخیره</button></form>; })}</article>) : <p role="status">ابتدا یک فراخوان ثبت کنید.</p>}</section>
  </div>;
}
