"use client";
import { useState, useTransition } from "react";
import { completeFacilitiesCompanyProfile, ensureFacilitiesProfileDocumentSlot, saveFacilitiesCompanyDraft } from "@/lib/actions/facilities-company";
import { showToast } from "@/components/ui/toast";

type Person = { id?: string; fullName: string; ownershipPercentage?: string; position?: string };
type Draft = { version: number; name: string; nationalId: string; registrationNumber: string; registrationPlace: string; registrationDate: string; registeredCapitalRial: string; contactFullName: string; contactNationalCode: string; shareholders: Person[]; officers: Person[] };
const emptyDraft: Draft = { version: 0, name: "", nationalId: "", registrationNumber: "", registrationPlace: "", registrationDate: "", registeredCapitalRial: "", contactFullName: "", contactNationalCode: "", shareholders: [], officers: [] };
export function CompanyProfileForm({ initial, locked = false }: { initial: Draft | null; locked?: boolean }) {
  const [draft, setDraft] = useState<Draft>(initial ?? emptyDraft);
  const [pending, start] = useTransition();
  const [errors, setErrors] = useState<string[]>([]);
  const update = (key: keyof Draft, value: string) => setDraft((current) => ({ ...current, [key]: value }));
  async function save() { start(async () => { try { const company = await saveFacilitiesCompanyDraft(draft); setDraft((current) => ({ ...current, version: company.profileVersion })); setErrors([]); showToast({ type: "success", message: "پیش‌نویس ذخیره شد" }); } catch (e) { const message = e instanceof Error ? e.message : "ذخیره ناموفق بود"; setErrors([message]); showToast({ type: "error", message }); } }); }
  async function upload(kind: string, officerId?: string) { try { const binding = await ensureFacilitiesProfileDocumentSlot(kind, officerId); const picker = document.createElement("input"); picker.type = "file"; picker.accept = officerId ? ".zip" : ".pdf,.doc,.docx,.xls,.xlsx,.csv,.zip"; picker.onchange = async () => { const file = picker.files?.[0]; if (!file) return; const body = new FormData(); body.set("bindingId", binding.id); body.set("idempotencyKey", crypto.randomUUID().replaceAll("-", "")); body.set("file", file); const response = await fetch("/api/facilities/profile-files", { method: "POST", body }); const data = await response.json(); if (!response.ok || data.lifecycleStatus !== "PASSED") throw new Error(data.error || "فایل هنوز قابل استفاده نیست"); showToast({ type: "success", message: "مدرک با موفقیت بررسی و ثبت شد" }); }; picker.click(); } catch (e) { showToast({ type: "error", message: e instanceof Error ? e.message : "بارگذاری ناموفق بود" }); } }
  function list(kind: "shareholders" | "officers") { return <fieldset className="profile-list"><legend>{kind === "shareholders" ? "سهام‌داران" : "مدیرعامل و اعضای هیئت‌مدیره"}</legend>{draft[kind].map((item, index) => <div className="profile-row" key={item.id ?? index}><input aria-label="نام" value={item.fullName} onChange={(e) => setDraft((d) => ({ ...d, [kind]: d[kind].map((x, i) => i === index ? { ...x, fullName: e.target.value } : x) }))} /> <input aria-label={kind === "shareholders" ? "درصد مالکیت" : "سمت"} inputMode={kind === "shareholders" ? "decimal" : undefined} value={kind === "shareholders" ? item.ownershipPercentage : item.position} onChange={(e) => setDraft((d) => ({ ...d, [kind]: d[kind].map((x, i) => i === index ? { ...x, [kind === "shareholders" ? "ownershipPercentage" : "position"]: e.target.value } : x) }))} />{kind === "officers" && item.id ? <button type="button" className="button button--ghost" onClick={() => upload("officer", item.id)}>ZIP هویتی</button> : null}<button type="button" className="button button--ghost" aria-label="حذف ردیف" onClick={() => setDraft((d) => ({ ...d, [kind]: d[kind].filter((_, i) => i !== index) }))}>حذف</button></div>)}<button type="button" className="button button--ghost" onClick={() => setDraft((d) => ({ ...d, [kind]: [...d[kind], kind === "shareholders" ? { fullName: "", ownershipPercentage: "" } : { fullName: "", position: "" }] }))}>افزودن</button></fieldset>; }
  const fields: Array<[keyof Draft, string]> = [["name", "نام شرکت"], ["nationalId", "شناسه ملی"], ["registrationNumber", "شماره ثبت"], ["registrationPlace", "محل ثبت"], ["registrationDate", "تاریخ ثبت"], ["registeredCapitalRial", "سرمایه ثبت‌شده (ریال)"], ["contactFullName", "نام و نام خانوادگی رابط"], ["contactNationalCode", "کد ملی رابط"]];
  if (locked) return <section className="panel" role="status"><h2>پروفایل شرکت موقتاً قفل است</h2><p>تا پایان پرداخت یا بررسی پرونده فعال، اطلاعات و مدارک پروفایل قابل تغییر نیست. اصلاحات درخواست تسهیلات را از صفحه همان پرونده انجام دهید.</p></section>;
  return <form className="panel profile-form" onSubmit={(e) => { e.preventDefault(); save(); }} noValidate>{errors.length ? <div role="alert" className="form-error">{errors.join(" ")}</div> : null}<div className="profile-grid">{fields.map(([key, label]) => <label key={key}>{label}<input value={draft[key] as string} dir={key.includes("Id") || key.includes("Capital") ? "ltr" : undefined} inputMode={key.includes("Id") || key.includes("Capital") ? "numeric" : undefined} onChange={(e) => update(key, e.target.value)} /></label>)}</div>{list("shareholders")}{list("officers")}<fieldset className="profile-list"><legend>مدارک شرکت</legend>{[["incorporation-notice", "آگهی تأسیس"], ["articles-of-association", "اساسنامه"], ["board-changes-gazette", "روزنامه رسمی تغییرات هیئت‌مدیره"], ["capital-increase-gazette", "روزنامه رسمی افزایش سرمایه"]].map(([kind, label]) => <button className="button button--ghost" type="button" key={kind} onClick={() => upload(kind)}>{label}</button>)}</fieldset><div className="sticky-actions"><button className="button button--primary" disabled={pending}>ذخیره پیش‌نویس</button><button type="button" className="button button--ghost" disabled={pending} onClick={() => start(async () => { try { await completeFacilitiesCompanyProfile({ version: draft.version }); showToast({ type: "success", message: "پروفایل شرکت کامل شد" }); } catch (e) { setErrors([e instanceof Error ? e.message : "تکمیل ناموفق بود"]); } })}>تأیید تکمیل پروفایل</button></div></form>;
}
