"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useMemo, useState, useTransition } from "react";
import { createFacilitiesDraft, ensureFacilitiesApplicationSlot, saveFacilitiesDraftDetails } from "@/lib/actions/facilities-application";
import { showToast } from "@/components/ui/toast";
const docs = ["tax-1404|اظهارنامه مالیاتی", "financial-1404|صورت مالی حسابرسی‌شده", "insurance|لیست بیمه", "trial-general|تراز کل ۱۴۰۵", "trial-subsidiary|تراز معین ۱۴۰۵", "credit-company|گزارش شرکت", "credit-ceo|گزارش مدیرعامل", "credit-board|گزارش عضو هیئت‌مدیره", "questionnaire|پرسشنامه تکمیل‌شده (فقط Word)", "licences|مجوزها و گواهی‌ها (ZIP)", "active-contracts|قراردادهای فعال (ZIP)", "vat-1404|ارزش افزوده ۱۴۰۴ (ZIP)"].map((value) => { const [key, label] = value.split("|"); return { key, label }; });
export function FacilitiesApplicationWizard({ data }: { data: any }) {
 const [pending,start]=useTransition(); const [intakeId,setIntakeId]=useState(data.intakes[0]?.id||""); const intake=useMemo(()=>data.intakes.find((x:any)=>x.id===intakeId),[data,intakeId]); const [supplierId,setSupplierId]=useState(intake?.supplierConfigurations[0]?.id||""); const [app,setApp]=useState(data.applications[0]||null); const [amount,setAmount]=useState(""); const [type,setType]=useState("FIXED_CAPITAL"); const [employeeCount,setEmployeeCount]=useState("0"); const [boardOfficerId,setBoardOfficerId]=useState("");
 const run=(work:()=>Promise<any>)=>start(async()=>{try{const result=await work();if(result?.id)setApp(result);showToast({type:"success",message:"پیش‌نویس ذخیره شد"});}catch(e){showToast({type:"error",message:e instanceof Error?e.message:"عملیات ناموفق بود؛ صفحه را تازه‌سازی کنید"});}});
 async function upload(key:string,file:File){if(!app)return;try{const kind=key.startsWith("tax-")?"tax":key.startsWith("financial-")?"financial":key.startsWith("vat-")?"vat":key;const binding=await ensureFacilitiesApplicationSlot({applicationId:app.id,kind,year:Number(key.split("-")[1])||undefined});const form=new FormData();form.set("bindingId",binding.id);form.set("idempotencyKey",crypto.randomUUID().replaceAll("-",""));form.set("file",file);const res=await fetch("/api/facilities/application-files",{method:"POST",body:form});const result=await res.json();if(!res.ok||result.lifecycleStatus!=="PASSED")throw new Error(result.error||"فایل در حال بررسی است؛ دوباره تلاش کنید");showToast({type:"success",message:"فایل بررسی و ثبت شد"});}catch(e){showToast({type:"error",message:e instanceof Error?e.message:"بارگذاری ناموفق بود"});}}
 if(!data.intakes.length)return <div className="panel" role="status">در حال حاضر دوره یا تأمین‌کننده واجد شرایطی برای درخواست وجود ندارد.</div>;
 if(!app)return <form className="panel profile-form" onSubmit={(e)=>{e.preventDefault();run(()=>createFacilitiesDraft({intakeId,intakeSupplierId:supplierId,facilityType:type as any,requestedAmountRial:amount}));}}><h2>شروع درخواست</h2><label>دوره<select value={intakeId} onChange={(e)=>{setIntakeId(e.target.value);setSupplierId(data.intakes.find((x:any)=>x.id===e.target.value)?.supplierConfigurations[0]?.id||"");}}>{data.intakes.map((x:any)=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>تأمین‌کننده<select value={supplierId} onChange={(e)=>setSupplierId(e.target.value)}>{intake.supplierConfigurations.map((x:any)=><option value={x.id} key={x.id}>{x.supplier.name}</option>)}</select></label>{intake.supplierConfigurations.map((x:any)=>x.id===supplierId?<a className="button button--ghost" href={`/api/facilities/questionnaires/${x.questionnaireTemplateVersion.id}?intakeSupplierId=${x.id}`} key={x.id}>دانلود پرسشنامه، نسخه {x.questionnaireTemplateVersion.versionLabel}</a>:null)}<label>نوع تسهیلات<select value={type} onChange={(e)=>setType(e.target.value)}><option value="FIXED_CAPITAL">سرمایه ثابت</option><option value="WORKING_CAPITAL">سرمایه در گردش</option></select></label><label>مبلغ درخواستی (ریال)<input dir="ltr" required inputMode="numeric" value={amount} onChange={(e)=>setAmount(e.target.value)}/><small>سقف: {intake.maximumAmountRial} ریال</small></label><button className="button button--primary" disabled={pending}>ایجاد پیش‌نویس</button></form>;
 const officers=app.officers?.filter((x:any)=>!x.isChiefExecutive)||[]; return <div className="profile-form"><section className="panel"><h2>مدارک درخواست</h2><p role="status">هر فایل حداکثر ۲۵ مگابایت و مجموع مدارک حداکثر ۱۵۰ مگابایت است.</p>{docs.map((doc)=><label className="profile-row" key={doc.key}><span>{doc.label}</span><input type="file" disabled={pending} accept={doc.key==="questionnaire"?".doc,.docx":doc.key.includes("vat")||["licences","active-contracts"].includes(doc.key)?".zip":".pdf,.doc,.docx,.xls,.xlsx,.csv,.zip"} onChange={(e)=>{const file=e.target.files?.[0];if(file)void upload(doc.key,file);}}/></label>)}</section><section className="panel"><h2>اطلاعات تکمیلی</h2><label>تعداد کارکنان<input inputMode="numeric" value={employeeCount} onChange={(e)=>setEmployeeCount(e.target.value)}/></label><label>عضو هیئت‌مدیره<select value={boardOfficerId} onChange={(e)=>setBoardOfficerId(e.target.value)}><option value="">انتخاب کنید</option>{officers.map((x:any)=><option key={x.id} value={x.id}>{x.fullName} — {x.position}</option>)}</select></label><button className="button button--primary" disabled={pending} onClick={()=>run(()=>saveFacilitiesDraftDetails({applicationId:app.id,employeeCount:Number(employeeCount),boardOfficerId}))}>تأیید کامل بودن پیش‌نویس</button><p>پرداخت و ارسال در این مرحله انجام نمی‌شود.</p></section></div>;
}
